language: node_js
node_js:
  - 10
env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.24.0
    - GCLOUD_STORAGE_BUCKET: kit-dev-images
    - SESSION_SECRET: sgdfgjkhsdfg
    - DB_USER: postgres
    - DB_DATABASE: postgres
    - DB_HOST: db
    - DB_PORT: 5432
before_script:
  - docker-compose up --build -d
script:
  - docker-compose exec app npm run test
after_script:
  - docker-compose down
