version: '3'
services:
  app:
    build: .
    command: ['npm', 'run', 'dev']
    volumes:
      - .:/usr/src/kit
    ports:
      - '8000:8000'
      - '8888:8888'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GCLOUD_STORAGE_BUCKET=kit-prod-images
      - SESSION_SECRET=sgdfgjkhsdfg
      - DB_USER=postgres
      - DB_DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - MAILGUN_API_KEY=doesntexist
      - VERIFICATION_SECRET=89se4jgsouidjgs
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
    ports:
      - '5433:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
