version: '3'
services:
  app:
    build: .
    command: ['npm', 'run', 'dev']
    volumes:
      - .:/usr/src/kit
    ports:
      - '8000:8000'
      - '8888:8888'
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
    ports:
      - '5433:5432'
